---
- hosts:
    all

  tasks:
    # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    - name: Add Hashicorp GPG apt Key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - name: Add Hashicorp Repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Update apt and install Vault
      apt:
        update_cache: true
        state: present # manage a version here
        name: vault

    # distribute vault hcl config file to all nodes

    - name: Manage the Vault service
      ansible.builtin.service:
        name: vault
        state: started
        enabled: yes

    # https://learn.hashicorp.com/tutorials/vault/raft-deployment-guide?in=vault/day-one-raft#prepare-tls-certificates

    # /etc/vault.d/vault.hcl
